apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clamav
  labels:
    k8s-app: clamav-host-scanner
spec:
  selector:
    matchLabels:
      name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: clamav-scanner
        image: edunick/clamav:latest
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        #- name: data-vol
          #mountPath: /data
        - name: host-fs
          mountPath: /host-fs
          readOnly: true
        - name: logs
          mountPath: /logs
        readinessProbe:
          exec:
            command:
              - /start.sh
          initialDelaySeconds: 60
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          #initialDelaySeconds: 30
      #terminationGracePeriodSeconds: 30
      volumes:
      #- name: data-vol
        #emptyDir: {}
      - name: host-fs
        hostPath:
          path: /
      - name: logs
        hostPath:
          path: /var/log/clamav
