apiVersion: apps/v1
kind: Deployment
metadata:
  name: srt-deployment
spec:
  selector:
    matchLabels:
      app: srt
  replicas: 5
  template:
    metadata:
      labels:
        app: srt
    spec:
      containers:
      - name: srt
        image: edunick/srt:latest
        ports:
        - containerPort: 8010
        env:
        - name: WORDPRESS_DB_NAME
          value: "srt_prd"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_HOST
          value: "unicorndev.ca3kduvqsxfv.us-east-1.rds.amazonaws.com:3306"
        - name: WORDPRESS_DB_PASSWORD
          value: "sportinos2019"
        - name: WORDPRESS_HOME
          value: "https://perforacionesbrasil.com.ar/shopper-recommendation-tool"
        volumeMounts:
        - name: s1
          mountPath: /var/www/html	
      volumes:
      - name: s1
        hostPath:
          path: /developer/s1		
